[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ultra-calculator"
version = "0.1.0"
description = "A collection of calculators and mathematical solvers."
requires-python = ">=3.11"
dependencies = [
    "InquirerPy"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]